### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by liyang53719** [INTEW/NSRR#1]
Thank you for reproducing this paper. It helped me a lot.

And I want to know, do we have any other way to download besides jbox?
Baidu Cloud or Google Drive？
Since I am not a student at school, I cannot access your cloud disk.

thank you

**Comment by INTEW** [comment]
thanks for reminding me, and I have updated the download links just now.

**Comment by liyang53719** [comment]
It works.
Thanks a lot!
